<?php

return array (
  'site_name' => 'Auge',
  'logo' => '#000000',
  'page_title' => 'Compre direto da industria',
  'page_description' => 'Agora a sua Empresa pode comprar direto da indústria com os preços de Fábrica. Elimine os atravessadores, com o aplicativo da Auge você vai poder comprar de forma fácil e muito rápido.',
  'site_locale' => 'pt-br',
  'domain' => 'augeapp.com.br',
  'page_keywords' => NULL,
  'scripts' => NULL,
  'mail_address' => 'info@augeapp.com.br',
  'mail_password' => 'op5Ww7_8',
  'mail_receive' => 'auge@augeapp.com',
  'facebook' => 'augeapp',
  'instagram' => 'augeapp',
  'youtube' => 'augeapp',
  'linkedin' => NULL,
  'telegram' => NULL,
  'whatsapp' => '(31) 3213-2204',
  'phone_one' => '(31) 99318-2412',
  'phone_two' => '(31) 3213-2204',
  'document' => '07.558.145/0001-51',
  'contact_mail' => 'info@augeapp.com.br',
  'address' => 'Av. Contorno 5436 - Savassi - Belo Horizonte - MG',
  'maps_link' => 'https://goo.gl/maps/JtKjBgHW6TsU7JsP6',
  'favicon' => 'uploads/config/favicon/favicon-222.png',
  'page_image' => 'uploads/config/image/auge-308.jpg',
  'page_image_dimensions' => '800x800',
  'color_primary' => '#000000',
);
